# This is a basic workflow to help you get started with Actions

name: Build Test Dev

# Controls when the workflow will run
# This workflow is triggered on pushes to the dev branch only.
on:
  pull_request:
   types: [closed]
   branches:
      dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2-beta
        with: 
          node-version: ${{ matrix.node }}

      - name: npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build and
          echo deploy your project.
